package postpass

// SqlResponse encapsulates a response generated by a worker
type SqlResponse struct {
	err    bool
	result string
}

// WorkItem encapsulates a job sent to a worker
type WorkItem struct {
	request       string
	output_format string
	response      chan SqlResponse
	closer        chan struct{}
}
