package postpass

import "time"

// SqlResponse encapsulates a response generated by a worker
type SqlResponse struct {
	err            bool
	result         string
	in_queue       time.Duration
	query_duration time.Duration
	est_cost       int

	// What queue was this put in
	queue string
}

// WorkItem encapsulates a job sent to a worker
type WorkItem struct {
	request     string
	geojson     bool
	response    chan SqlResponse
	closer      chan struct{}
	when_queued time.Time
	est_cost    int

	// What queue was this put in
	queue string
}
